imagesNamespace: argoproj
controllerImage: workflow-controller
executorImage: argoexec
imagesTag: v2.1.0-alpha1
controllerName: workflow-controller

# Enables ability to SSH into pod using web UI
enableWebConsole: false
ui:
  image: argoui
  serviceType: LoadBalancer
  ingress:
    enabled: false
    annotations: {}
    hosts: []
    tls: []
crdVersion: v1alpha1

# If set to true then chart set controller instance id to release name
useReleaseAsInstanceID: false
instanceID:

useDefaultArtifactRepo: false
useStaticCredentials: true

# If set to true then chart installs minio and generate according artifactRepository section in workflow controller config map
installMinio: true
minioBucketName: argo-artifacts

artifactRepository:
  s3:
    accessKeySecret:
      key: accesskey
    secretKeySecret:
      key: secretkey
    insecure: true
