apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: ui
          image: "{{ .Values.imagesNamespace }}/{{ .Values.ui.image }}:{{ .Values.imagesTag }}"
          env:
          - name: IN_CLUSTER
            value: "true"
